### ISSUE TITLE
Wrong use of IsInventoryItemLocked

### ISSUE THREAD

**Issue by melbaa** [RagedUnicorn/wow-vanilla-gearmenu#22]
I believe
https://github.com/RagedUnicorn/wow-vanilla-gearmenu/blob/50080cc23aaf5a7fb3e9dba8d6e7d964845a025d/Code/GM_ItemHelper.lua#L186

should be slotId, not bagPos.

Noticed it because I have 36 slot bags and there aren't that many inventory slots, so this errors out.

Probably the same issue https://github.com/RagedUnicorn/wow-vanilla-gearmenu/issues/20

**Comment by RagedUnicorn** [comment]
Hi @melbaa,

Did you try the suggestions I made in that referenced ticket. I can't test this myself because I don't have an account to test this. Besides that I don't really know why this would run into an error because the size of the bags is not hardcoded but retrieved from what the Blizzard Api tells the addon.

Cheers,
RagedUnicorn

**Comment by RagedUnicorn** [comment]
Fixed with release 1.2.2 - 5 years since last release :O
